sudo: required
services:
  - docker

before_install:
  - docker build -t anirban1980/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anirban1980/react-test npm test -- --coverage

after_success:
  - docker build -t anirban1980/multi-client ./client
  - docker build -t anirban1980/multi-nginx ./nginx
  - docker build -t anirban1980/multi-server ./server
  - docker build -t anirban1980/multi-worker ./worker
  # log in to docker CLI
  # DOCKER_ID and DOCKER_PASSWORD are stored as env vars in travis UI similar to aws elasic beanstalk access keys
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push anirban1980/multi-client
  - docker push anirban1980/multi-nginx
  - docker push anirban1980/multi-server
  - docker push anirban1980/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-403065120601"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY